### ISSUE TITLE
Flow control

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby-lang.github.io#1]
Currrently we only have `if statement`'s introduction in flow control section. We'll also need:

- case statement
- while loop
- the `break` keyword

**Comment by hachi8833** [comment]
Updated https://github.com/goby-lang/cheatsheets/blob/cdab67dc5b03cf0dc8efa2ea29934291545ea5a6/goby.md
Closing by now

**Comment by st0012** [comment]
Can you also update them to this repo?
