### ISSUE TITLE
Builtin Types docs

### ISSUE THREAD

**Issue by st0012** [goby-lang/goby-lang.github.io#2]
Currently we don't have enough people and time to maintain normal API documents.

So what we should do now is to group some of the types into one page. And only briefly introduce the types and put a link to their source code files (which have API document comments). For example:

- `String and Integer`
- `Boolean and Null`
- `Array and Concurrent Array`
- `Hash and Concurrent Hash`
- ...etc.

**Comment by hachi8833** [comment]
I think adding a glossary would also help people.

**Comment by hachi8833** [comment]
Updated https://github.com/goby-lang/cheatsheets/blob/cdab67dc5b03cf0dc8efa2ea29934291545ea5a6/goby.md
Closing for now.
